# Generated by Django 6.0.2 on 2026-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='description',
            field=models.TextField(blank=True, help_text='Description or notes for this purchase item', null=True),
        ),
    ]
