# Generated by Django 6.0.2 on 2026-03-03 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_add_description_to_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
