# Generated by Django 6.0.2 on 2026-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of the event', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='event_location',
            field=models.CharField(blank=True, help_text='Event Venue/Location', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='event_name',
            field=models.CharField(blank=True, help_text='Event Name (e.g. Wedding of X)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateField(blank=True, help_text='Expected return date of items', null=True),
        ),
    ]
