# Generated by Django 6.0.2 on 2026-02-17 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotationitem_product_name_alter_quotation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(default=datetime.date(2026, 3, 4)),
        ),
    ]
