# Generated by Django 6.0.2 on 2026-02-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_alter_quotation_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CONVERTED', 'Converted to Order'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
