# Generated by Django 6.0.2 on 2026-03-03 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_alter_quotation_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(default=datetime.date(2026, 3, 18)),
        ),
    ]
