# Generated by Django 6.0.2 on 2026-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_quotation_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='pricing_type',
            field=models.CharField(choices=[('PER_DAY', 'Per Day'), ('PER_EVENT', 'Per Event'), ('FIXED', 'Fixed Price')], default='PER_DAY', max_length=20),
        ),
    ]
