# Generated by Django 6.0.2 on 2026-03-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_alter_quotation_valid_until'),
        ('vendors', '0004_alter_vendor_area_alter_vendor_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner from whom this item is intended to be rented', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_quotations', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='partner_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate expected from the partner', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='rented_from_partner',
            field=models.BooleanField(default=False, help_text='Whether this item is rented from a partner'),
        ),
    ]
