# Generated by Django 6.0.2 on 2026-03-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_quotationitem_partner_quotationitem_partner_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
