# Generated by Django 6.0.2 on 2026-02-09 12:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_event_date_order_event_location_and_more'),
        ('products', '0005_product_is_consumable_product_is_rental_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Return'), ('PARTIAL', 'Partially Returned'), ('COMPLETE', 'Fully Returned')], default='PENDING', max_length=20)),
                ('responsibility', models.CharField(choices=[('CUSTOMER', 'Customer Side'), ('INTERNAL', 'Internal / Staff'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('damage_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_return', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rental_return',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_sent', models.PositiveIntegerField(help_text='Quantity sent to event')),
                ('qty_returned', models.PositiveIntegerField(default=0, help_text='Quantity returned in good condition')),
                ('qty_damaged', models.PositiveIntegerField(default=0)),
                ('qty_missing', models.PositiveIntegerField(default=0)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('rental_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.rentalreturn')),
            ],
        ),
    ]
