# Generated by Django 6.0.2 on 2026-02-13 19:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_event_date_order_event_location_and_more'),
        ('products', '0006_product_quantity_damaged'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recovery_type', models.CharField(choices=[('CUSTOMER_DEDUCTION', 'Deducted from Customer Payment'), ('CUSTOMER_PAYMENT', 'Separate Customer Payment'), ('INSURANCE', 'Insurance Claim'), ('STAFF_DEDUCTION', 'Deducted from Staff Salary'), ('WRITE_OFF', 'Written Off')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'damage_recovery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rentalreturn',
            name='damage_recovered',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount recovered for damages', max_digits=12),
        ),
        migrations.AddField(
            model_name='rentalreturn',
            name='is_stock_restored',
            field=models.BooleanField(default=False, help_text='Whether owned stock has been restored'),
        ),
        migrations.AddField(
            model_name='rentalreturn',
            name='total_items_damaged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentalreturn',
            name='total_items_missing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentalreturn',
            name='total_items_returned',
            field=models.PositiveIntegerField(default=0, help_text='Total items returned in good condition'),
        ),
        migrations.AddField(
            model_name='rentalreturn',
            name='total_items_sent',
            field=models.PositiveIntegerField(default=0, help_text='Total item quantity sent to event'),
        ),
        migrations.AddField(
            model_name='rentalreturnitem',
            name='damage_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charge for damaged/missing items', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='rentalreturnitem',
            unique_together={('rental_return', 'product')},
        ),
        migrations.AddIndex(
            model_name='rentalreturn',
            index=models.Index(fields=['status'], name='rental_retu_status_0b87f2_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalreturn',
            index=models.Index(fields=['order'], name='rental_retu_order_i_aa8195_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalreturn',
            index=models.Index(fields=['return_date'], name='rental_retu_return__ac9aca_idx'),
        ),
        migrations.AlterModelTable(
            name='rentalreturnitem',
            table='rental_return_item',
        ),
        migrations.AddField(
            model_name='damagerecovery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagerecovery',
            name='rental_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='returns.rentalreturn'),
        ),
    ]
