# Generated by Django 6.0.2 on 2026-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_damagerecovery_rentalreturn_damage_recovered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalreturnitem',
            name='is_partner_item',
            field=models.BooleanField(default=False),
        ),
    ]
