# Generated by Django 6.0.2 on 2026-03-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_quantity_damaged'),
        ('returns', '0003_rentalreturnitem_is_partner_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalreturnitem',
            unique_together={('rental_return', 'product', 'is_partner_item')},
        ),
    ]
