# Generated by Django 6.0.2 on 2026-02-09 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
        ('products', '0002_product_barcode_product_sku_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_consumable',
            field=models.BooleanField(default=False, help_text='Whether this is a consumable tool (Tapes, Cable Ties)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_rental',
            field=models.BooleanField(default=True, help_text='Whether this is a rental item (Lights, DJ) or a consumable tool'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('PER_DAY', 'Per Day'), ('PER_EVENT', 'Per Event')], default='PER_DAY', help_text='Rental pricing model', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique Tag or Serial Number for the equipment', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_location',
            field=models.CharField(blank=True, help_text='Physical location (e.g., Rack A, Room 2, Warehouse 1)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Product color (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, help_text='Material/Fabric type (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces',
            field=models.JSONField(blank=True, default=list, help_text='Product components/pieces'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['serial_number'], name='product_serial__ae4407_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['warehouse_location'], name='product_warehou_8dd639_idx'),
        ),
    ]
