# Generated by Django 6.0.2 on 2026-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_consumable_product_is_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_damaged',
            field=models.PositiveIntegerField(default=0, help_text='Quantity currently marked as damaged'),
        ),
    ]
