# Generated by Django 6.0.2 on 2026-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_quantity_damaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when stock becomes free again (e.g. return_date)', null=True),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when stock starts being busy (e.g. event_date)', null=True),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='reserved_until',
            field=models.DateTimeField(help_text='When this reservation expires (Legacy field, use dates for rentals)'),
        ),
    ]
