# Generated by Django 6.0.2 on 2026-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='reason_or_item',
            field=models.TextField(blank=True, default='', help_text='Reason for lending money or item description'),
        ),
    ]
