# Generated by Django 6.0.2 on 2026-02-16 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payments', '0002_initial'),
        ('labors', '0003_salaryslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='source_id',
            field=models.CharField(blank=True, help_text='ID of the source record in the source module', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='source_module',
            field=models.CharField(blank=True, help_text='Module that created this advance (e.g., EXPENSES)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['source_module', 'source_id'], name='advance_pay_source__2770bf_idx'),
        ),
    ]
