# Generated by Django 6.0.2 on 2026-02-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_event_date_order_event_location_and_more'),
        ('payables', '0003_payable_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Linked order if payable originated from partner rental items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_payables', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payable',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('PURCHASE', 'From Purchase'), ('PARTNER_RENTAL', 'From Partner Rental')], default='MANUAL', help_text='How this payable was generated', max_length=20),
        ),
    ]
