# Generated by Django 6.0.2 on 2026-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0004_payable_order_payable_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes and payment history', null=True),
        ),
        migrations.AlterField(
            model_name='payablepayment',
            name='notes',
            field=models.TextField(blank=True, help_text='Payment notes', null=True),
        ),
    ]
