# Generated by Django 6.0.2 on 2026-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0005_alter_payable_notes_alter_payablepayment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='reason_or_item',
            field=models.TextField(blank=True, default='', help_text='Description of what was borrowed for'),
        ),
    ]
