# Generated by Django 6.0.2 on 2026-02-15 14:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('salary_date', models.DateField(default=django.utils.timezone.now)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_advances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Other deductions', max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, help_text='Incentives/Bonuses', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='labors.labor')),
            ],
            options={
                'ordering': ['-year', '-month', 'labor__name'],
                'unique_together': {('labor', 'month', 'year')},
            },
        ),
    ]
