# Generated by Django 6.0.2 on 2026-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0003_salaryslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='fixed_incentive',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed monthly incentive/bonus for the employee', max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
