# Generated by Django 6.0.2 on 2026-03-03 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0004_labor_fixed_incentive_salaryslip_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='salary_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
