# Generated by Django 6.0.2 on 2026-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0005_alter_salaryslip_salary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='caste',
            field=models.CharField(blank=True, help_text='Caste/community of the labor', max_length=100, null=True),
        ),
    ]
