# Generated by Django 6.0.2 on 2026-02-13 19:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0003_order_event_date_order_event_location_and_more'),
        ('sales', '0010_make_payment_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining amount due', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid against this invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Associated order (optional if sale-based)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='write_off_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount written off for invoice closure', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(blank=True, help_text='Associated sale (optional if order-based)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.sales'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WRITTEN_OFF', 'Written Off'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current invoice status', max_length=20),
        ),
    ]
