# Generated by Django 6.0.2 on 2026-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_invoice_amount_due_invoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WRITTEN_OFF', 'Written Off'), ('CLOSED', 'Closed')], default='DRAFT', help_text='Current invoice status', max_length=20),
        ),
    ]
