# Generated by Django 6.0.1 on 2026-01-13 08:48

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense', models.CharField(help_text='Expense title/name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the expense')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('withdrawal_by', models.CharField(choices=[('Mr. Shahzain Baloch', 'Mr. Shahzain Baloch'), ('Mr Huzaifa', 'Mr Huzaifa')], help_text='Who authorized/made the withdrawal', max_length=50)),
                ('date', models.DateField(help_text='Date of expense')),
                ('time', models.TimeField(help_text='Time of expense')),
                ('category', models.CharField(blank=True, help_text='Optional expense category', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='For soft deletion')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expense',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
