# Generated by Django 6.0.2 on 2026-02-15 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('labors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deductible_labor',
            field=models.ForeignKey(blank=True, help_text='Employee whose salary will be deducted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductible_expenses', to='labors.labor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this a recurring monthly expense?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_salary_deductible',
            field=models.BooleanField(default=False, help_text='Is this expense deductible from employee salary?'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_recurring'], name='expense_is_recu_3edc57_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_salary_deductible'], name='expense_is_sala_4048a0_idx'),
        ),
    ]
