# Generated by Django 6.0.2 on 2026-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_deductible_labor_expense_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='withdrawal_by',
            field=models.CharField(blank=True, choices=[('Mr. Shahzain Baloch', 'Mr. Shahzain Baloch'), ('Mr Huzaifa', 'Mr Huzaifa')], help_text='Who authorized/made the withdrawal', max_length=50, null=True),
        ),
    ]
