# Generated by Django 6.0.2 on 2026-02-19 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='area',
            field=models.CharField(blank=True, help_text='Area/locality within the city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(blank=True, help_text='Name of the business/company', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, help_text='City where vendor is located', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
