# Generated by Django 6.0.2 on 2026-02-13 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days for rental'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per unit/day at time of order', max_digits=12),
        ),
    ]
