# Generated by Django 6.0.2 on 2026-02-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0004_remove_orderitem_unit_price_orderitem_days_and_more'),
        ('vendors', '0003_alter_vendor_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner from whom this item is rented', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_rentals', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='partner_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate charged by the partner', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rented_from_partner',
            field=models.BooleanField(default=False, help_text='Whether this item is rented from a partner'),
        ),
    ]
