# Generated by Django 6.0.2 on 2026-03-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0006_alter_orderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pricing_type',
            field=models.CharField(choices=[('PER_DAY', 'Per Day'), ('PER_EVENT', 'Per Event'), ('FIXED', 'Fixed Price')], default='PER_DAY', help_text='Pricing model for this item', max_length=20),
        ),
    ]
